name: 'Deploy'

on:
  pull_request:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'first'
      - run: echo ${{ github.ref_name }}

  approval:
    environment: Production
    needs: first
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'approval'

  deploy:
    environment: Production
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'deploy'