name: 'Deploy'

on:
  pull_request:
  workflow_dispatch:

jobs:
  approval:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Approved'

  deploy:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'