name: 'Deploy'

on:
  pull_request:
  workflow_dispatch:

jobs:
  approval:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: |
          echo 'Approved'
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}
          echo github.sha: ${{ github.sha }}
          echo github.ref: ${{ github.ref }}
          echo github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}
          echo github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}
          echo github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}
          echo github.event.pull_request.base.sha: ${{ github.event.pull_request.base.sha }}
          echo github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}
          echo github.event.pull_request.base.repo.full_name: ${{ github.event.pull_request.base.repo.full_name }}

  deploy:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'