name: 'DispatchWorkflow'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check out'
        required: true
        default: 'develop'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_ICON_EMOJI: ":exclamation:"
          SLACK_TITLE: ":exclamation: 通知テスト"
          SLACK_COLOR: '#d50000'
