name: push on develop

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      ref: ${{ github.sha }}

  temp-check-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   ref: '4fcf428391e42e5ea92e128d7844d3f8a358bfc7'

  echo:
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT: ${{ toJson(github.event) }}
      GITHUB_HEAD_COMMIT: ${{ toJson(github.event.head_commit) }}
      GITHUB_HEAD_COMMIT_MODIFIED: ${{ toJson(github.event.head_commit.modified) }}
    steps:
      - name: Echo
        run: echo $GITHUB_EVENT && echo $GITHUB_HEAD_COMMIT && echo $GITHUB_HEAD_COMMIT_MODIFIED

  check_modified_files:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.modified, '.github/workflows/push_on_main.yml') }}
    steps:
      - name: Echo
        run: 
          echo ${{ github.event }}
          echo ${{ github.event.head_commit }}
          echo ${{ github.event.head_commit.modified }}
