name: Reusable Workflow

on:
  workflow_call:
    inputs:
      ref:
        description: ''
        required: true
        type: string

jobs:
  check_checkout:
    runs-on: ubuntu-20.04
    name: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
